-- Rollback of 20260910000100_institution_guards: triggers and functions.
drop trigger if exists os_inst_events_guard on public.os_inst_events;
drop trigger if exists os_inst_evaluation_runs_guard on public.os_inst_evaluation_runs;
drop trigger if exists os_inst_evaluation_rubrics_owner_guard on private.os_inst_evaluation_rubrics;
drop trigger if exists os_inst_evaluations_owner_guard on public.os_inst_evaluations;
drop trigger if exists os_inst_submissions_guard on public.os_inst_submissions;
drop trigger if exists os_inst_debates_guard on public.os_inst_debates;
drop trigger if exists os_inst_reviews_guard on public.os_inst_reviews;
drop trigger if exists os_inst_briefs_guard on public.os_inst_briefs;
drop trigger if exists os_inst_corpus_guard on public.os_inst_corpus;
drop trigger if exists os_inst_agent_versions_guard on public.os_inst_agent_versions;
drop trigger if exists os_lab_agents_lane_at_birth on public.os_lab_agents;
drop trigger if exists os_lab_agents_prompt_lock on public.os_lab_agents;
drop function if exists public.os_inst_events_guard();
drop function if exists public.os_inst_brief_decide(uuid, text, text);
drop function if exists public.os_inst_eval_rubric(uuid);
drop function if exists public.os_inst_eval_score(uuid);
drop function if exists public.os_inst_evaluation_runs_guard();
drop function if exists public.os_inst_evaluations_owner_guard();
drop function if exists public.os_inst_submissions_guard();
drop function if exists public.os_inst_debates_guard();
drop function if exists public.os_inst_reviews_guard();
drop function if exists public.os_inst_briefs_guard();
drop function if exists public.os_inst_corpus_guard();
drop function if exists public.os_inst_version_set_eval(uuid, text, numeric);
drop function if exists public.os_inst_version_reject(uuid, text);
drop function if exists public.os_inst_version_promote(uuid);
drop function if exists public.os_inst_agent_versions_guard();
drop function if exists public.os_lab_agents_lane_at_birth();
drop function if exists public.os_lab_agents_prompt_lock();
drop function if exists public.os_inst_committee_slug();
drop function if exists public.os_inst_guc_on(text);
