/**
 * Proves the port is faithful rather than merely plausible.
 *
 * Two independent guards:
 *
 *  1. TEMPLATES and LOOPS are pinned by SHA-256 over their JSON serialisation.
 *     Reword one gate criterion and this fails. That is the point — the criteria
 *     are the methodology, so a "tidy-up" is a behaviour change.
 *
 *  2. Every prompt builder is diffed against golden output generated by running
 *     the ORIGINAL console's own functions in Node over a synthetic project
 *     (see __fixtures__/console-golden.json). A paraphrase anywhere in a prompt
 *     body fails here.
 *
 * The fixture content is entirely synthetic. No real research question, claim,
 * evidence value, source or log entry appears in this repo.
 */
import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import golden from './__fixtures__/console-golden.json';
import { LOOPS, LOOP_KEYS } from './loops';
import { TEMPLATES, TPL_KEYS, gatesFor } from './templates';
import {
  citeCount,
  critIND,
  curStage,
  dueLoops,
  loopDue,
  nextAction,
  parkCandidate,
  stageStatus,
  staleItems,
  type StageState,
} from './pipeline';
import {
  prAllBatch,
  prBatch,
  prBrief,
  prCite,
  prContra,
  prData,
  prDigest,
  prHand,
  prLit,
  prMethod,
} from './prompts';
import type {
  Project,
  ResearchProject,
  ResearchSettings,
  ResearchItem,
  ResearchClaim,
} from '../../data/types';

const sha = (value: unknown) =>
  createHash('sha256').update(JSON.stringify(value)).digest('hex');

// The exact date the golden output was generated at, so date-dependent prompts
// (handover snapshot, digest header, staleness) reproduce byte for byte.
const NOW = new Date('2026-07-25T12:00:00Z');
const SETTINGS: ResearchSettings = { wipLimit: 2, staleMonths: 12 };

describe('ported specification objects', () => {
  it('TEMPLATES is byte-identical to the console source', () => {
    expect(sha(TEMPLATES)).toBe(
      '42255180a61159a5c2ebb9bd4b5e4bcdc01e209891b27c90df13ab14942f72e0',
    );
  });

  it('LOOPS is byte-identical to the console source', () => {
    expect(sha(LOOPS)).toBe(
      '0935d927f9211fa7061c52b3bfb0e2dd0ac249e4846967282c1f5ff5c00c0a91',
    );
  });

  it('carries all five families in order, with every stage and criterion', () => {
    expect(TPL_KEYS).toEqual(['sim', 'emp', 'slr', 'policy', 'min']);
    const stages = TPL_KEYS.reduce((n, key) => n + TEMPLATES[key].stages.length, 0);
    const criteria = TPL_KEYS.reduce(
      (n, key) =>
        n + TEMPLATES[key].stages.reduce((m, stage) => m + stage.g.length, 0),
      0,
    );
    expect(stages).toBe(32);
    expect(criteria).toBe(95);
  });

  it('carries all three loops with their full checklists', () => {
    expect(LOOP_KEYS).toEqual(['data', 'cite', 'method']);
    const checks = LOOP_KEYS.reduce((n, key) => n + LOOPS[key].check.length, 0);
    expect(checks).toBe(21);
    // Every loop states why it recurs and where its framework comes from.
    LOOP_KEYS.forEach((key) => {
      expect(LOOPS[key].why.length).toBeGreaterThan(80);
      expect(LOOPS[key].ref.length).toBeGreaterThan(20);
      expect(LOOPS[key].trig.length).toBeGreaterThan(40);
    });
  });

  it('every stage carries input, process, output and at least one gate', () => {
    TPL_KEYS.forEach((key) => {
      TEMPLATES[key].stages.forEach((stage) => {
        expect(stage.n).toMatch(/^\d\d$/);
        expect(stage.t.length).toBeGreaterThan(0);
        expect(stage.i.length).toBeGreaterThan(0);
        expect(stage.p.length).toBeGreaterThan(0);
        expect(stage.o.length).toBeGreaterThan(0);
        expect(stage.g.length).toBeGreaterThan(0);
      });
    });
  });
});

// ---------------------------------------------------------------------------
// The synthetic fixture, mirrored into the app's own shapes
// ---------------------------------------------------------------------------

function project(over: Partial<Project> & { id: string; title: string }): Project {
  return {
    domain: 'growth',
    type: 'research',
    status: 'active',
    milestones: [],
    order: 1,
    ...over,
  } as Project;
}

function item(over: Partial<ResearchItem> & { name: string }): ResearchItem {
  return {
    id: over.name,
    projectId: 'alpha',
    unit: '',
    type: 'parameter',
    crit: false,
    status: 'IND',
    value: '',
    source: '',
    asof: '',
    note: '',
    order: 0,
    ...over,
  } as ResearchItem;
}

function claim(over: Partial<ResearchClaim> & { text: string }): ResearchClaim {
  return { id: over.text, projectId: 'alpha', layer: 'c', ev: '', order: 0, ...over } as ResearchClaim;
}

function alpha(): ResearchProject {
  const gates = gatesFor('sim');
  gates[0] = [true, true, true, true];
  gates[1] = [true, false, false];
  return {
    project: project({
      id: 'alpha',
      title: 'Alpha study',
      priority: 1,
      deadline: '2027-03-01',
      status: 'active',
    }),
    meta: {
      projectId: 'alpha',
      template: 'sim',
      question: 'Under what conditions does effect X hold?',
      output: 'Working paper',
      audience: 'Seminar',
      gates,
    },
    items: [
      item({ name: 'Discount rate', unit: '%', crit: true, status: 'V', value: '7.5', source: 'Publisher A, Table 2', asof: '2024', note: 'nominal, pre-tax' }),
      item({ name: 'Capacity factor', unit: '%', crit: true, note: 'needed for the frontier' }),
      item({ name: 'Reference dataset', type: 'dataset' }),
      item({ name: 'Method paper', type: 'paper', status: 'V', source: 'Journal B 2019', asof: '2019' }),
      item({ name: 'Stale figure', unit: 'unit', type: 'baseline', status: 'V', value: '12', source: 'Publisher C', asof: '2015' }),
    ],
    claims: [
      claim({ text: 'Baseline claim carried from earlier work.', layer: 'a', ev: 'Publisher A' }),
      claim({ text: 'Verified finding with a source attached.', layer: 'b', ev: 'Journal B 2019' }),
      claim({ text: 'Working hypothesis, unverified.', layer: 'c' }),
    ],
    log: [
      { id: 'l1', projectId: 'alpha', date: '2026-01-05', text: 'Chose the simulation family over an empirical design.' },
      { id: 'l2', projectId: 'alpha', date: '2026-02-11', text: 'Rejected a panel specification: no usable variation.' },
    ],
    cycles: [
      { id: 'd1', projectId: 'alpha', loop: 'data', n: 1, date: '2026-03-01', verdict: 'clean', findings: 'No change at source.', itemCount: 4, citeCount: 2, invalidated: 0, backLabel: '' },
      { id: 'm1', projectId: 'alpha', loop: 'method', n: 1, date: '2026-01-20', verdict: 'rework', findings: 'Circularity in the outcome definition.', itemCount: 3, citeCount: 1, invalidated: 2, backLabel: '02' },
    ],
  };
}

function beta(): ResearchProject {
  return {
    project: project({ id: 'beta', title: 'Beta study', priority: 3, status: 'parked', order: 2 }),
    meta: {
      projectId: 'beta',
      template: 'slr',
      question: 'What is already known about Y?',
      output: 'Review',
      audience: 'Internal',
      gates: gatesFor('slr'),
    },
    items: [
      item({ id: 'j1', projectId: 'beta', name: 'Discount rate', unit: '%', status: 'V', value: '9.0', source: 'Publisher D', asof: '2023' }),
      item({ id: 'j2', projectId: 'beta', name: 'Capacity factor', unit: '%', crit: true }),
    ],
    claims: [],
    log: [],
    cycles: [],
  };
}

// The console's badge classes, mapped onto our state names.
const STATE_FOR_CLS: Record<string, StageState> = {
  'b-block': 'blocked',
  'b-pass': 'passed',
  'b-open': 'open',
  'b-lock': 'locked',
};

describe('prompt builders match the console byte for byte', () => {
  const a = alpha();
  const all = [alpha(), beta()];

  it('prBrief', () => expect(prBrief(a)).toBe(golden.prBrief));
  it('prBatch', () => expect(prBatch(a)).toBe(golden.prBatch));
  it('prAllBatch', () => expect(prAllBatch(all)).toBe(golden.prAllBatch));
  it('prData', () => expect(prData(a, SETTINGS, NOW)).toBe(golden.prData));
  it('prCite', () => expect(prCite(a)).toBe(golden.prCite));
  it('prMethod', () => expect(prMethod(a)).toBe(golden.prMethod));
  it('prLit', () => expect(prLit(a)).toBe(golden.prLit));
  it('prContra', () => expect(prContra(a)).toBe(golden.prContra));
  it('prHand', () => expect(prHand(a, SETTINGS, NOW)).toBe(golden.prHand));
  it('prDigest', () => expect(prDigest(all, SETTINGS, NOW)).toBe(golden.prDigest));
});

describe('pipeline logic matches the console', () => {
  const a = alpha();

  it('curStage, citeCount and nextAction agree', () => {
    expect(curStage(a)).toBe(golden.logic.curStage);
    expect(citeCount(a)).toBe(golden.logic.citeCount);
    expect(nextAction(a).text).toBe(golden.logic.nextAction);
  });

  it('critIND and staleItems agree', () => {
    expect(critIND(a).map((x) => x.name)).toEqual(golden.logic.critIND);
    expect(staleItems(a, SETTINGS, NOW).map((x) => x.name)).toEqual(
      golden.logic.staleItems,
    );
  });

  it('stageStatus agrees on state and wording for the first four stages', () => {
    [0, 1, 2, 3].forEach((index) => {
      const mine = stageStatus(a, index);
      const theirs = golden.logic.stageStatus[index];
      expect(mine.txt).toBe(theirs.txt);
      expect(mine.state).toBe(STATE_FOR_CLS[theirs.cls]);
    });
  });

  it('loopDue agrees on due-ness and reason for all three loops', () => {
    (['data', 'cite', 'method'] as const).forEach((loop) => {
      const mine = loopDue(a, loop, SETTINGS, NOW);
      const theirs = golden.logic.loopDue[loop];
      expect(mine.due).toBe(theirs.due);
      expect(mine.why).toBe(theirs.why);
    });
    expect(dueLoops(a, SETTINGS, NOW)).toEqual(golden.logic.dueLoops);
  });

  it('parkCandidate picks the same project', () => {
    expect(parkCandidate([alpha(), beta()])?.project.title).toBe(
      golden.logic.parkCandidate,
    );
  });
});
